language: python
python:
  - "3.6"
cache: pip
install:
  - curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
  - source /etc/lsb-release
  - echo "deb https://repos.influxdata.com/${DISTRIB_ID,,} ${DISTRIB_CODENAME} stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  - sudo apt-get update
  - sudo apt-get install -y influxdb
  - sudo service influxdb start
  - pip install -r requirements.txt
  - cp -fv config.sample.py config.py
script:
  - python test/test_influx.py
